import { Player, DraftPick, DraftProspect, FreeAgent } from "./types";

export const currentRosterData: Player[] = [
  {
    id: "cade-cunningham",
    name: "Cade Cunningham",
    number: "#2",
    position: "PG",
    age: 24,
    height: "6'6\"",
    weight: "220 lbs",
    experience: "4 Years",
    ppg: 23.5,
    rpg: 4.8,
    apg: 7.9,
    per: 19.8,
    ts: 54.8,
    impactGrade: "A",
    strengths: ["Pick-and-Roll Creation", "Mid-Range Scoring", "Elite Size at PG", "Decisive Playmaking"],
    weaknesses: ["Turnover Rate", "High-Usage Fatigue", "Off-the-dribble 3PT Efficiency"],
    analysis: "Cade Cunningham is the franchise cornerstone. His elite combination of height, vision, and pacing makes him one of the most promising pure playmakers in the league. While his efficiency is sometimes hampered by the lack of dynamic secondary shot-creators around him, he remains a master operator out of pick-and-roll schemes. Limiting his turnovers and managing his load are key to unlocking his celestial upside.",
    howToOptimize: "Pair Cunningham with a high-gravity secondary ball-handler who can shoot off-the-catch, allowing Cade to preserve energy and attack bent defenses. Adding a elite rim-running screen setter will also elevate his lob assist numbers.",
    salary: "$35.1M",
    darko: 2.8,
    lebron: 2.4,
    epm: 3.1
  },
  {
    id: "jaden-ivey",
    name: "Jaden Ivey",
    number: "#23",
    position: "SG / PG",
    age: 24,
    height: "6'4\"",
    weight: "195 lbs",
    experience: "3 Years",
    ppg: 18.2,
    rpg: 3.4,
    apg: 3.8,
    per: 15.6,
    ts: 56.1,
    impactGrade: "B",
    strengths: ["Blazing First Step", "Transition Threat", "Rim Pressure", "Secondary Creation"],
    weaknesses: ["Defensive Positioning", "Inconsistent Catch-and-shoot 3PT", "Mid-Range Settling"],
    analysis: "Jaden Ivey provides the electric, north-south speed that perfectly complements Cunningham's deliberate tempo. His ability to collapse defenses and get to the free-throw line creates high-value paint touches. Under proper coaching, his off-ball relocation and decision-making have matured, though defensive focus remains a project.",
    howToOptimize: "Utilize Ivey in double-drag transition concepts. He excels on closeout attacks when defenses are pre-occupied with Cunningham. Off-season focus should be strictly dedicated to standard corner 3-point shooting and screen navigation.",
    salary: "$8.0M",
    darko: 0.8,
    lebron: 0.5,
    epm: 0.7
  },
  {
    id: "tobias-harris",
    name: "Tobias Harris",
    number: "#12",
    position: "PF",
    age: 33,
    height: "6'8\"",
    weight: "226 lbs",
    experience: "14 Years",
    ppg: 15.4,
    rpg: 6.2,
    apg: 2.8,
    per: 14.2,
    ts: 55.4,
    impactGrade: "B-",
    strengths: ["Veteran Savvy", "Mid-post Isolation", "Defensive Versatility", "Locker Room Leadership"],
    weaknesses: ["Slow Shot Release", "Contract-to-Production Ratio", "Low Defensive Rebound Rate"],
    analysis: "Returned to Detroit to provide the roster with desperate spacing, veteran maturity, and low-turnover half-court scoring. Harris is a reliable professional who doesn't make mistakes, but at his age, he is better suited as a solid third or fourth scoring option rather than a heavy load-bearer.",
    howToOptimize: "Use him as an escape-valve scorer in late shot-clock mid-post situations. Focus on utilizing him as a pick-and-pop spacer rather than allowing him to stagnate possessions with slow-forming isolation attempts.",
    salary: "$25.3M",
    darko: -0.2,
    lebron: -0.5,
    epm: -0.4
  },
  {
    id: "jalen-duren",
    name: "Jalen Duren",
    number: "#0",
    position: "C",
    age: 22,
    height: "6'10\"",
    weight: "250 lbs",
    experience: "3 Years",
    ppg: 12.8,
    rpg: 11.2,
    apg: 2.4,
    per: 18.2,
    ts: 62.5,
    impactGrade: "B",
    strengths: ["Elite Rebounding", "Lob-Threat Gravity", "Generational Physicality", "Underrated Passing"],
    weaknesses: ["Free-throw Shooting", "Defensive Rim Protection positioning", "High Foul Rate"],
    analysis: "Duren is a physical marvel who averages a double-double with ease. He possesses soft hands, quick leaping instincts, and a reliable post-presence. His frontcourt vision is highly advanced for his age. However, his rim-protection block metrics and pick-and-roll defensive coverage must take a major leap to anchor a top-10 team defense.",
    howToOptimize: "Develop a drop-coverage scheme that emphasizes verticality. Limit his isolation defensive assignments and pair him with a shot-blocking power forward (e.g. Isaiah Stewart in spurts or a dynamic draft target) to cover his vertical recoveries.",
    salary: "$5.1M",
    darko: 0.1,
    lebron: -0.2,
    epm: -0.1
  },
  {
    id: "ausar-thompson",
    name: "Ausar Thompson",
    number: "#9",
    position: "SF / PF",
    age: 23,
    height: "6'7\"",
    weight: "215 lbs",
    experience: "2 Years",
    ppg: 8.8,
    rpg: 6.4,
    apg: 1.9,
    per: 13.5,
    ts: 51.2,
    impactGrade: "B-",
    strengths: ["All-Defense Level Wing Stopping", "Generational Athleticism", "Weakside Shot Blocking", "Offensive Rebounding"],
    weaknesses: ["Outside Shooting Gravity", "Half-court ball handling", "Finishing touch through contact"],
    analysis: "Ausar is an absolute terror on the defensive side of the basketball, possessing the lateral agility to guard points guards and the vertical leap to block centers at the rim. His offensive rebounding generates constant extra possessions. Unfortunately, teams actively ignore him behind the 3-point line, severely cramping Detroit's spacing.",
    howToOptimize: "Utilize Ausar as a short-roll playmaker (screener in Cunningham's P&Rs) and dunker-spot baseline cutter. Surround him with three elite catch-and-shoot threats at all times to negate his lack of gravity on the perimeter.",
    salary: "$8.4M",
    darko: 1.1,
    lebron: 1.6,
    epm: 1.2
  },
  {
    id: "ron-holland",
    name: "Ron Holland II",
    number: "#00",
    position: "SF",
    age: 20,
    height: "6'8\"",
    weight: "206 lbs",
    experience: "Rookie",
    ppg: 10.2,
    rpg: 4.5,
    apg: 1.6,
    per: 12.8,
    ts: 52.5,
    impactGrade: "C+",
    strengths: ["Relentless Motor", "Transition Scoring", "Defensive Intensity", "Slashing Aggression"],
    weaknesses: ["Half-court Shot Creation", "Pull-up 3-pointer consistency", "Inexperience-driven Fouls"],
    analysis: "Holland brings a high-octane energy and a physical slashing mindset to the Pistons' young core. He loves to push in transition, attacks the rim with fearlessness, and pesters high-scoring opponents defensively. Like Ausar, his perimeter shot is a work in progress, but his athletic package is undeniable.",
    howToOptimize: "Keep him running in early offense secondary breaks. Focus his developmental reps on standard catch-and-shoot corner threes to keep defenders from dropping into the paint.",
    salary: "$8.8M",
    darko: -0.5,
    lebron: -0.8,
    epm: -0.7
  },
  {
    id: "isaiah-stewart",
    name: "Isaiah Stewart",
    number: "#28",
    position: "C / PF",
    age: 25,
    height: "6'8\"",
    weight: "250 lbs",
    experience: "6 Years",
    ppg: 9.5,
    rpg: 6.8,
    apg: 1.5,
    per: 13.1,
    ts: 58.4,
    impactGrade: "C+",
    strengths: ["High-intensity Switch Defense", "Respectable 3PT Spacing", "Interior Toughness", "Screen setting"],
    weaknesses: ["Vertical Rim Protection", "Post-up shot creation", "Offensive rebound decline"],
    analysis: "Stewart, affectionally known as 'Beef Stew', is the physical backbone of the team. He has successfully morphed from a traditional post center to a reliable pick-and-pop spacer (shooting ~37% from deep) and versatile switch defender who can stay in front of elite perimeter players.",
    howToOptimize: "Deploy him as an off-the-bench utility backup big who can slot next to Jalen Duren in jumbo line-ups or play as a small-ball center to pull opposing rim protectors out of the paint.",
    salary: "$15.0M",
    darko: -0.1,
    lebron: 0.2,
    epm: 0.1
  },
  {
    id: "malik-beasley",
    name: "Malik Beasley",
    number: "#5",
    position: "SG",
    age: 29,
    height: "6'4\"",
    weight: "187 lbs",
    experience: "10 Years",
    ppg: 11.4,
    rpg: 2.5,
    apg: 1.4,
    per: 12.1,
    ts: 59.2,
    impactGrade: "B-",
    strengths: ["Elite Catch-and-Shoot Gravity", "Transition Wing Running", "Quick Releases"],
    weaknesses: ["On-ball defense", "Inside finishing", "Playmaking limits"],
    analysis: "Beasley has been an exceptional addition, giving the team a premium catch-and-shoot high-volume spacer. Opposing defenders dare not leave him, creating pristine operating lanes for Cade Cunningham. He has a highly professional, fast release and runs transition routes with extreme discipline.",
    howToOptimize: "Run him off hammer-screens and floppy actions. He should never be asked to initiate offense, but rather be set up as a primary shooter on weakside relocations.",
    salary: "$6.0M",
    darko: 0.3,
    lebron: 0.1,
    epm: 0.2
  },
  {
    id: "simone-fontecchio",
    name: "Simone Fontecchio",
    number: "#19",
    position: "SF",
    age: 30,
    height: "6'8\"",
    weight: "209 lbs",
    experience: "4 Years",
    ppg: 10.1,
    rpg: 3.2,
    apg: 1.5,
    per: 12.9,
    ts: 58.0,
    impactGrade: "C+",
    strengths: ["Slick Off-ball Cut Shooting", "High IQ Relocation", "Size on Wing Defending"],
    weaknesses: ["Off-the-dribble creator", "Athletic rim protection", "Defending elite dribble speeds"],
    analysis: "The Italian wing is an exceptional standard team-space utility player. He handles relocations, cuts with precise vertical intent, and hits contested wing threes. Defensively, he matches size well and executes weakside helper duties with reliable intelligence.",
    howToOptimize: "Deploy him in secondary units as a primary spacer, or run stretch line-ups where he plays as a stretch four next to Cunningham and Duren.",
    salary: "$8.0M",
    darko: 0.2,
    lebron: -0.1,
    epm: -0.1
  },
  {
    id: "marcus-sasser",
    name: "Marcus Sasser",
    number: "#25",
    position: "PG",
    age: 25,
    height: "6'2\"",
    weight: "195 lbs",
    experience: "3 Years",
    ppg: 7.2,
    rpg: 1.5,
    apg: 2.6,
    per: 11.6,
    ts: 55.1,
    impactGrade: "C",
    strengths: ["Microwave Scoring", "Pull-up 3-pointers", "On-ball defensive pest"],
    weaknesses: ["Size limitations at PG", "Traditional playmaking vision", "In-paint finishing"],
    analysis: "Sasser is a classic sparkplug point guard who can heat up in secondary units. He has an outstanding lateral stance on defense and shoots a gorgeous high-arcing deep pull-up. He lacks natural elite table-setter vision, playing more like a tiny scoring guard.",
    howToOptimize: "Let him run alongside a bigger playmaking wing (like Ausar or a playmaking FA) so he can focus purely on scoring aggression and locking down rival backup points.",
    salary: "$2.7M",
    darko: -0.8,
    lebron: -1.2,
    epm: -1.0
  }
];

export const upcomingDraftPicks: DraftPick[] = [
  {
    id: "dp-2026-1",
    year: 2026,
    round: 1,
    originalOwner: "Detroit",
    notes: "Protected for picks 1-9. Highly likely to be retained based on current lottery calculations."
  },
  {
    id: "dp-2026-2",
    year: 2026,
    round: 2,
    originalOwner: "Detroit",
    notes: "Slightly high value among 2nd round options, top of the tier."
  },
  {
    id: "dp-2027-1",
    year: 2027,
    round: 1,
    originalOwner: "Detroit",
    notes: "Unprotected primary future asset."
  },
  {
    id: "dp-2027-2",
    year: 2027,
    round: 2,
    originalOwner: "Minnesota (via trade)",
    notes: "Acquired during previous standard draft day draft manipulations."
  }
];

export const draftProspectsData: DraftProspect[] = [
  {
    id: "prospect-aj-dybantsa",
    name: "AJ Dybantsa",
    position: "SF",
    collegeOrTeam: "BYU",
    age: 19,
    height: "6'9\"",
    scoutingGrade: "99 (Generational)",
    projectedRange: "No. 1 Pick Overall",
    projectedPpg: 22.4,
    projectedRpg: 6.8,
    projectedApg: 3.5,
    strengths: ["Generational Wing Shot-Creation", "Elite Mid-Range Pullup", "Unstoppable Iso Scoring", "Defensive Fluidity"],
    weaknesses: ["Half-court volume shot selection", "High-deflective focus under heavy double teams"],
    fitAnalysis: "AJ Dybantsa is a franchise-catalyzing alpha scorer. At 6'9\", his shot-creation is unguardable, and slotting him on Detroit's wing next to Cade Cunningham creates a superstar duo that would tear opposing half-court defenses to shreds while providing versatile defensive length next to Ausar Thompson.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-cam-boozer",
    name: "Cameron Boozer",
    position: "PF",
    collegeOrTeam: "Duke",
    age: 18,
    height: "6'9\"",
    scoutingGrade: "98 (Generational)",
    projectedRange: "Picks 1 - 2",
    projectedPpg: 20.5,
    projectedRpg: 10.2,
    projectedApg: 2.8,
    strengths: ["Elite Basketball IQ", "Dominant Interior Scoring", "Slick High-Low Passing", "Excellent Rebounding Base"],
    weaknesses: ["Speed vs perimeter small-ball fours", "Vertical launch shot-block timing"],
    fitAnalysis: "Cameron Boozer represents the ultimate high-IQ modern big. He brings a professional-grade physical foundation, elite rebounding, and spacing potential. Slotting him alongside Jalen Duren creates an incredibly robust, high-activity frontline that provides immediate paint dominance.",
    primaryBenefit: "size"
  },
  {
    id: "prospect-darryn-peterson",
    name: "Darryn Peterson",
    position: "SG / PG",
    collegeOrTeam: "Kansas",
    age: 19,
    height: "6'5\"",
    scoutingGrade: "96 (Elite)",
    projectedRange: "Picks 2 - 4",
    projectedPpg: 19.2,
    projectedRpg: 5.1,
    projectedApg: 4.5,
    strengths: ["Elite Physical Bulk Guard", "Three-Level Shot-Creation", "Slick Secondary Playmaking", "Physical Guard Defense"],
    weaknesses: ["Off-ball defensive relocations", "Left-hand finish focus"],
    fitAnalysis: "Peterson is a powerhouse combo guard who can overwhelm smaller guards. His half-court isolation scoring and pick-and-roll orchestration make him the ideal secondary handler next to Cade Cunningham, letting Cunningham play off-ball and saving Cade's energy for the clutch.",
    primaryBenefit: "playmaking"
  },
  {
    id: "prospect-caleb-wilson",
    name: "Caleb Wilson",
    position: "PF",
    collegeOrTeam: "North Carolina",
    age: 19,
    height: "6'9\"",
    scoutingGrade: "95 (Elite)",
    projectedRange: "Picks 3 - 5",
    projectedPpg: 16.4,
    projectedRpg: 8.8,
    projectedApg: 2.4,
    strengths: ["Elite Defensive Versatility", "Great Spacing Potential", "Relentless Motor", "Slick Secondary Rim Protection"],
    weaknesses: ["Half-court handle tightness", "Post physical backdowns"],
    fitAnalysis: "Wilson is the perfect prototype for the modern multi-positional defense-first power forward. He covers ground effortlessly, locks down wings, and provides weakside rim-protection. This directly answers Detroit's PF defensive issues and forms a dynamic partnership with Jalen Duren.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-koa-peat",
    name: "Koa Peat",
    position: "PF",
    collegeOrTeam: "Arizona",
    age: 19,
    height: "6'8\"",
    scoutingGrade: "94 (Great)",
    projectedRange: "Picks 4 - 7",
    projectedPpg: 15.8,
    projectedRpg: 7.6,
    projectedApg: 3.2,
    strengths: ["Elite Physical Strength", "Slick Interior Passing", "Slick Mid-Post Faceup", "High-Motor Defender"],
    weaknesses: ["Outside shooting consistency", "Lateral speed against elite handlers"],
    fitAnalysis: "Peat is a highly mature physical specimen. He facilitates exceptionally well from the elbows and brings postseason-ready toughness. He can operate as an elite connector forward on the baseline, using his playmaking to set up Jalen Duren for easy dunks.",
    primaryBenefit: "size"
  },
  {
    id: "prospect-nate-ament",
    name: "Nate Ament",
    position: "SF / PF",
    collegeOrTeam: "Virginia",
    age: 19,
    height: "6'9\"",
    scoutingGrade: "95 (Great)",
    projectedRange: "Picks 3 - 6",
    projectedPpg: 17.5,
    projectedRpg: 6.2,
    projectedApg: 2.1,
    strengths: ["Elite Shooting Mechanics", "Generational Touch at 6'9\"", "Slick Weakside Spacing", "Terrific High Release"],
    weaknesses: ["Lower body mass", "Defensive screen navigation"],
    fitAnalysis: "Ament is a premier draft-class spacer. An elite hybrid forward with soft touch from way downtown. Detroit desperately needs his elite gravity to unlock driving lanes for Ivey and Cunningham.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-meleek-thomas",
    name: "Meleek Thomas",
    position: "SG",
    collegeOrTeam: "Arkansas",
    age: 19,
    height: "6'4\"",
    scoutingGrade: "93 (Very Good)",
    projectedRange: "Picks 5 - 9",
    projectedPpg: 18.1,
    projectedRpg: 4.2,
    projectedApg: 3.5,
    strengths: ["Dynamic Pull-Up Game", "Fearless Paint Aggression", "Pest-like On-Ball Defense", "Excellent Clutch Timing"],
    weaknesses: ["High turnover variance", "Static off-ball watchiness"],
    fitAnalysis: "Thomas is a high-octane scoring guard. He introduces real fire and elite transition pacing off the bench. He can play as a microwave asset who relieves scoring dry-spells.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-jasper-johnson",
    name: "Jasper Johnson",
    position: "PG / SG",
    collegeOrTeam: "Kentucky",
    age: 19,
    height: "6'4\"",
    scoutingGrade: "93 (Very Good)",
    projectedRange: "Picks 5 - 10",
    projectedPpg: 16.8,
    projectedRpg: 3.1,
    projectedApg: 4.2,
    strengths: ["Lethal Deep Range Shooting", "Elite Ball Handling Speed", "Slick Baseline Cuts", "Pick-and-Roll Vision"],
    weaknesses: ["Slight frame", "Physical defense on big guards"],
    fitAnalysis: "Johnson brings extreme 3-point range gravity that forces defense expansion. He can run the backup backcourt or seamlessly coexist with Cunningham as an elite off-ball movement marksman.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-brayden-burries",
    name: "Brayden Burries",
    position: "SG",
    collegeOrTeam: "Arizona",
    age: 19,
    height: "6'4\"",
    scoutingGrade: "92 (Great)",
    projectedRange: "Picks 7 - 12",
    projectedPpg: 15.9,
    projectedRpg: 4.5,
    projectedApg: 2.8,
    strengths: ["Polished Scoring Polish", "Extremely Strong Frame", "High-IQ Backdoor Cutting", "Active Defensive Decelerations"],
    weaknesses: ["Vertical blast over rim", "Isolation trigger times"],
    fitAnalysis: "Burries is a strong, seasoned scoring wing. He provides immense secondary offensive stability and physical integrity that easily scales into an elite standard starting-caliber guard role.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-mikel-brown",
    name: "Mikel Brown Jr.",
    position: "PG",
    collegeOrTeam: "Kentucky",
    age: 18,
    height: "6'3\"",
    scoutingGrade: "92 (Great)",
    projectedRange: "Picks 6 - 11",
    projectedPpg: 14.2,
    projectedRpg: 2.5,
    projectedApg: 6.5,
    strengths: ["Elite Playmaking IQ", "Lethal Off-Screen Pullups", "Excellent Floater Touch", "Outstanding Pick-and-Roll Navigation"],
    weaknesses: ["Physical defense bulk", "Turnover rate under heavy traps"],
    fitAnalysis: "Brown is a pristine table-setter with incredible IQ. Having him anchor the secondary unit completely solves Detroit's backup playmaking issues, keeping the offense fluid while Cade Cunningham takes a break.",
    primaryBenefit: "playmaking"
  },
  {
    id: "prospect-jalen-haralson",
    name: "Jalen Haralson",
    position: "SF",
    collegeOrTeam: "Notre Dame",
    age: 19,
    height: "6'6\"",
    scoutingGrade: "92 (Great)",
    projectedRange: "Picks 8 - 14",
    projectedPpg: 15.2,
    projectedRpg: 5.5,
    projectedApg: 3.1,
    strengths: ["Physically Bulky Forward", "Strong Downhill Drive", "Versatile Guard Defender", "Reliable Soft Touch Float"],
    weaknesses: ["Static catch-and-shoot depth", "High dribble position"],
    fitAnalysis: "Haralson brings deep physical wing robustness. His size and multi-positional defense give Detroit great versatility on the perimeter, acting as a lock-down hybrid wing next to Ausar Thompson.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-bryson-tiller",
    name: "Bryson Tiller",
    position: "PF",
    collegeOrTeam: "Auburn",
    age: 19,
    height: "6'9\"",
    scoutingGrade: "91 (Very Good)",
    projectedRange: "Picks 10 - 15",
    projectedPpg: 14.5,
    projectedRpg: 8.1,
    projectedApg: 1.5,
    strengths: ["Excellent Positional Mass", "Superb Defensive Positioning", "Solid Glass Rebounding", "Tough Low-Post Wall"],
    weaknesses: ["Stretch range floor mapping", "Isolation self-creation limits"],
    fitAnalysis: "Tiller is a highly reliable baseline wall defender and rebounder. He covers defensive spacing errors and provides reliable interior support, bringing physical standard discipline next to Sasser or Beasley.",
    primaryBenefit: "size"
  },
  {
    id: "prospect-isiah-harwell",
    name: "Isiah Harwell",
    position: "SG",
    collegeOrTeam: "Houston",
    age: 19,
    height: "6'5\"",
    scoutingGrade: "91 (Very Good)",
    projectedRange: "Picks 10 - 15",
    projectedPpg: 13.8,
    projectedRpg: 4.1,
    projectedApg: 2.2,
    strengths: ["Lock-down Wing Stopping", "Slick Catch-and-Shoot Outlets", "Outstanding Help Recovery Speed", "Great Locker Room IQ"],
    weaknesses: ["Self-initiating drive bursts", "Pull-up distance limits"],
    fitAnalysis: "Harwell brings the tough-minded standard defensive identity of top Houston guards. He guards the opponent's best scorer, moves without ball lag, and serves as a premium spacing-defense guard.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-shelton-henderson",
    name: "Shelton Henderson",
    position: "SF / SG",
    collegeOrTeam: "Duke",
    age: 19,
    height: "6'6\"",
    scoutingGrade: "91 (Very Good)",
    projectedRange: "Picks 9 - 14",
    projectedPpg: 14.1,
    projectedRpg: 6.0,
    projectedApg: 2.8,
    strengths: ["Elite Downhill Motor", "Outstanding Muscle Thickness", "Tough Point-of-Attack Stopper", "High-activity Rebounding"],
    weaknesses: ["Perimeter release timing", "Free-throw consistency"],
    fitAnalysis: "Henderson is a physical powerhouse. He acts as a versatile physical wing stopper who absorbs contact with ease, mimicking Ausar Thompson's defensive grit but with highly physical slashing potential.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-tounde-yessoufou",
    name: "Tounde Yessoufou",
    position: "SF",
    collegeOrTeam: "Baylor",
    age: 19,
    height: "6'5\"",
    scoutingGrade: "90 (Very Good)",
    projectedRange: "Picks 12 - 18",
    projectedPpg: 15.0,
    projectedRpg: 5.8,
    projectedApg: 2.0,
    strengths: ["Explosive Athletic Energy", "Relentless Swarm Defending", "Lethal Off-cuts and Lobs", "Hard-nosed Screen Separator"],
    weaknesses: ["Contested deep shot attempts", "In-traffic turnovers"],
    fitAnalysis: "Yessoufou provides outstanding high-intensity athleticism. He loves fighting for loose balls and provides immense baseline physical coverage, lifting Detroit's second-unit energy.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-nyk-lewis",
    name: "Nyk Lewis",
    position: "PG",
    collegeOrTeam: "Xavier",
    age: 19,
    height: "6'2\"",
    scoutingGrade: "89 (Good Prospect)",
    projectedRange: "Picks 15 - 22",
    projectedPpg: 13.5,
    projectedRpg: 3.0,
    projectedApg: 5.1,
    strengths: ["On-ball Defensive Harassment", "Slick Mid-Range Escape Shot", "High-speed Floor Navigation", "Elite Screen Navigation"],
    weaknesses: ["High paint launch blocks", "Deep arc volume constraints"],
    fitAnalysis: "Lewis represents a fearless, competitive backup guard. He locks up opponent playmakers, bringing robust screen defense and a steady ball-distribution style.",
    primaryBenefit: "playmaking"
  },
  {
    id: "prospect-chris-cenac",
    name: "Chris Cenac",
    position: "C",
    collegeOrTeam: "LSU",
    age: 19,
    height: "6'10\"",
    scoutingGrade: "92 (Great)",
    projectedRange: "Picks 6 - 11",
    projectedPpg: 15.5,
    projectedRpg: 9.2,
    projectedApg: 1.8,
    strengths: ["Superb Vertical Rim Protection", "Mobile Baseline Range", "Fluid Transition Finishes", "Developing Pick-and-pop"],
    weaknesses: ["Post positioning foul rates", "High-intensity bulk strength"],
    fitAnalysis: "Cenac is an incredibly versatile modern forward-center. He blocks shots with spectacular timing and stretches the floor, opening spacing next to Jaden Ivey's hyper-drive.",
    primaryBenefit: "size"
  },
  {
    id: "prospect-dwayne-aristode",
    name: "Dwayne Aristode",
    position: "SF",
    collegeOrTeam: "Arizona",
    age: 19,
    height: "6'8\"",
    scoutingGrade: "90 (Very Good)",
    projectedRange: "Picks 12 - 18",
    projectedPpg: 12.5,
    projectedRpg: 4.5,
    projectedApg: 1.8,
    strengths: ["Elite Catch-and-Shoot 3PT", "Smart Off-Ball Cut Paths", "Excellent Spacing Gravity", "Active Wing Containment"],
    weaknesses: ["Isolation pull-up consistency", "Tight static floor handles"],
    fitAnalysis: "Aristode is the ultimate 3-and-D layout asset. He ensures defenders cannot cheat off the corners, providing critical spacing for Cade Cunningham to drive.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-kayden-mingo",
    name: "Kayden Mingo",
    position: "PG",
    collegeOrTeam: "Penn State",
    age: 18,
    height: "6'3\"",
    scoutingGrade: "89 (Good Prospect)",
    projectedRange: "Picks 18 - 25",
    projectedPpg: 14.8,
    projectedRpg: 3.2,
    projectedApg: 4.5,
    strengths: ["Exceptional Crafty Handles", "Smooth Pull-up Shot Release", "Outstanding Live-Dribble Passes", "Terrific Paint Deceleration"],
    weaknesses: ["Physical recovery vs tall guards", "Outside launch mechanics"],
    fitAnalysis: "Mingo brings crafty dribble pacing. He is super steady in high-stress situations, ensuring clean second-unit offense without turnovers.",
    primaryBenefit: "playmaking"
  },
  {
    id: "prospect-xavion-staton",
    name: "Xavion Staton",
    position: "C",
    collegeOrTeam: "BYU",
    age: 19,
    height: "7'0\"",
    scoutingGrade: "91 (Very Good)",
    projectedRange: "Picks 8 - 14",
    projectedPpg: 10.1,
    projectedRpg: 8.5,
    projectedApg: 0.6,
    strengths: ["Elite Vertical Shot-Blocking", "Phenomenal Defensive Recovery", "Excellent Target Hands", "Relentless Rim Runner"],
    weaknesses: ["Lower back baseline weight", "Raw scoring post-moves"],
    fitAnalysis: "Staton is a premier shot-blocking anchor. He seals the rim completely, providing elite pick-and-roll vertical rim defense to turn Detroit's backup paint into a standard fortress.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-kingston-flemings",
    name: "Kingston Flemings",
    position: "PG",
    collegeOrTeam: "Houston",
    age: 19,
    height: "6'3\"",
    scoutingGrade: "90 (Very Good)",
    projectedRange: "Picks 12 - 18",
    projectedPpg: 13.1,
    projectedRpg: 3.2,
    projectedApg: 5.8,
    strengths: ["Lethal Fastbreak Speeds", "Elite Drive-and-Kick Logic", "Exceptional Steal Disruption", "Hard-Nosed Competitor"],
    weaknesses: ["Perimeter catch-and-shoot depth", "Mid-range float choices"],
    fitAnalysis: "Flemings provides brilliant downhill pace. Perfect for accelerating secondary transition units and finding cutters, creating a beautiful fast-paced change of gears.",
    primaryBenefit: "playmaking"
  },
  {
    id: "prospect-nikola-khamenia",
    name: "Nikola Khamenia",
    position: "PF",
    collegeOrTeam: "Duke",
    age: 19,
    height: "6'8\"",
    scoutingGrade: "89 (Good Prospect)",
    projectedRange: "Picks 16 - 24",
    projectedPpg: 12.2,
    projectedRpg: 5.1,
    projectedApg: 3.0,
    strengths: ["Elite Court Vision Forward", "Smooth Corner 3PT Spacing", "Slick High-Post Orchestration", "High IQ Relocations"],
    weaknesses: ["Vertical defensive bounce", "Explosive paint drive recovery"],
    fitAnalysis: "Khamenia is an exceptional high-IQ connector forward. He can stretch the floor, execute flawless high-low feeds, and find guys on backdoors, enhancing general continuity.",
    primaryBenefit: "playmaking"
  },
  {
    id: "prospect-dante-allen",
    name: "Dante Allen",
    position: "SG",
    collegeOrTeam: "Villanova",
    age: 19,
    height: "6'4\"",
    scoutingGrade: "88 (Good Prospect)",
    projectedRange: "Picks 20 - 28",
    projectedPpg: 12.8,
    projectedRpg: 4.0,
    projectedApg: 2.5,
    strengths: ["Superb Perimeter Lockdown Defending", "Excellent Off-Ball Relocations", "High Positional Toughness", "Active Rebounding Instincts"],
    weaknesses: ["Isolation handle self-creations", "Speed blow-bys against tiny guards"],
    fitAnalysis: "Allen is a quintessential gritty Villanova guard. He guards multiple speeds and brings high shot-making discipline, fitting smoothly into Detroit's physical setup.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-kaden-house",
    name: "Kaden House",
    position: "SG",
    collegeOrTeam: "New Mexico",
    age: 19,
    height: "6'4\"",
    scoutingGrade: "88 (Good Prospect)",
    projectedRange: "Picks 22 - 30",
    projectedPpg: 15.1,
    projectedRpg: 4.8,
    projectedApg: 2.1,
    strengths: ["Elite Point-of-Attack Steals", "Polished High-Stakes Scoring", "Relentless Transition Slashes", "Terrific Lob Catching"],
    weaknesses: ["Overplaying gamble lane selections", "Outside jump mechanics"],
    fitAnalysis: "House is a high-octane perimeter disrupter. He forces massive turnovers and converts them instantly to transition dunks, generating cheap visual spark runs.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-sidy-gueye",
    name: "Sidy Gueye",
    position: "C",
    collegeOrTeam: "Alabama",
    age: 19,
    height: "6'10\"",
    scoutingGrade: "87 (Solid Prospect)",
    projectedRange: "Picks 24 - 32",
    projectedPpg: 9.8,
    projectedRpg: 8.2,
    projectedApg: 1.0,
    strengths: ["Exceptional Shot-Block Reach", "Outstanding Offensive Tip Rebounds", "Tough Screen Impact", "Mobile High-Tempo Roller"],
    weaknesses: ["Free throw line percentages", "Foul accumulation rates"],
    fitAnalysis: "Gueye is a classic high-motor screen setter and shot swatter. He mirrors Jalen Duren's athletic rim runs and would guarantee heavy backup paint control.",
    primaryBenefit: "size"
  },
  {
    id: "prospect-davion-hannah",
    name: "Davion Hannah",
    position: "SG / SF",
    collegeOrTeam: "Alabama",
    age: 19,
    height: "6'5\"",
    scoutingGrade: "88 (Good Prospect)",
    projectedRange: "Picks 20 - 28",
    projectedPpg: 13.5,
    projectedRpg: 4.2,
    projectedApg: 2.0,
    strengths: ["Elite Translational Agility", "Electric Baseline Explosion", "Excellent Passing Lane Anticipation", "Smooth Pull-up escape"],
    weaknesses: ["Half-court trigger pace stagnation", "High mass contact dunks"],
    fitAnalysis: "Hannah is a beautiful straight-line athlete. He provides great energy and physical perimeter coverage that increases team speed.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-efeosa-oliogu",
    name: "Efeosa Oliogu",
    position: "SF",
    collegeOrTeam: "Overtime Elite",
    age: 19,
    height: "6'6\"",
    scoutingGrade: "87 (Solid Prospect)",
    projectedRange: "Picks 25 - Second Round",
    projectedPpg: 12.4,
    projectedRpg: 4.0,
    projectedApg: 1.8,
    strengths: ["Generational Horizontal Agility", "Powerful Contact Slashing", "Excellent Steal Deflections", "Exceptional Muscle Force"],
    weaknesses: ["Outside shooting pullup depth", "Double team release time"],
    fitAnalysis: "Oliogu is an elite horizontal athlete from Canada. He plays with massive kinetic energy, breaking defensive walls off downhill cuts.",
    primaryBenefit: "defense"
  },
  {
    id: "prospect-michael-ruzic",
    name: "Michael Ruzic",
    position: "PF",
    collegeOrTeam: "Zadar (Croatia)",
    age: 19,
    height: "6'10\"",
    scoutingGrade: "89 (Good Prospect)",
    projectedRange: "Picks 15 - 25",
    projectedPpg: 11.8,
    projectedRpg: 5.4,
    projectedApg: 2.4,
    strengths: ["Superb Shooting Release at 6'10\"", "Elite European Standard IQ", "Slick Perimeter Pick-and-Pop", "Defensive Help Positioning"],
    weaknesses: ["Vertical blast blocks", "Speed recoveries on tiny guards"],
    fitAnalysis: "Ruzic is an incredibly talented Croatian stretch-four. He plays with the intelligence of a pro veteran, providing superb high-gravity spacing.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-dame-sarr",
    name: "Dame Sarr",
    position: "SG",
    collegeOrTeam: "Barcelona (Spain)",
    age: 20,
    height: "6'6\"",
    scoutingGrade: "88 (Good Prospect)",
    projectedRange: "Picks 18 - 28",
    projectedPpg: 12.0,
    projectedRpg: 3.5,
    projectedApg: 2.1,
    strengths: ["Lethal Catch-and-Shoot Range", "Terrific Wingspan Frame", "Excellent Passing Lane Feeds", "Smart Tactical Positionings"],
    weaknesses: ["Self-creation static off-dribbles", "Lower core drive weights"],
    fitAnalysis: "Sarr has elite EuroLeague exposure. He brings standard high-IQ floor mapping, hit-ahead passes, and high-gravity perimeter spacing.",
    primaryBenefit: "shooting"
  },
  {
    id: "prospect-hugo-moukouri",
    name: "Hugo Yimga Moukouri",
    position: "PF / C",
    collegeOrTeam: "INSEP (France)",
    age: 18,
    height: "6'9\"",
    scoutingGrade: "87 (Solid Prospect)",
    projectedRange: "Second Round",
    projectedPpg: 11.2,
    projectedRpg: 6.8,
    projectedApg: 1.4,
    strengths: ["Exceptional Physical Muscle Mass", "Fearless Paint Aggression", "Strong Target Hands near Block", "Mobile Floor Transitions"],
    weaknesses: ["High foul rates per minute", "Outside deep shooting range"],
    fitAnalysis: "Moukouri is a high-potential French physical anchor. He models his game after tough, bruising interior powerhouses, adding superb paint depth.",
    primaryBenefit: "size"
  }
];

export const freeAgentsData: FreeAgent[] = [
  {
    id: "fa-myles-turner",
    name: "Myles Turner",
    position: "C",
    currentTeam: "Indiana Pacers",
    age: 30,
    tier: "Max Target",
    projectedSalary: 28.5,
    ppg: 17.5,
    rpg: 7.1,
    apg: 1.3,
    strengths: ["Elite Rim Protection", "Reliable 3PT pick-and-pop", "High Playoff Experience"],
    weaknesses: ["Defensive Rebounding", "Individual Isolation Post play"],
    fitAnalysis: "Turner represents the absolute dream archetype next to Detroit's current pieces. He instantly solves Detroit's rim-protection issues (averages 2.0+ blocks) while dragging rival centers out of the paint due to his outstanding 3-point range, unlocking Jaden Ivey and Cade Cunningham's driving abilities.",
    primaryBenefit: "defense"
  },
  {
    id: "fa-brandon-ingram",
    name: "Brandon Ingram",
    position: "SF / PF",
    currentTeam: "New Orleans Pelicans",
    age: 28,
    tier: "Max Target",
    projectedSalary: 36.0,
    ppg: 21.3,
    rpg: 5.1,
    apg: 5.8,
    strengths: ["Elite Mid-Range Pullup", "Three-Level Scoring Isolation", "Secondary Playmaking"],
    weaknesses: ["Off-ball high-volume 3PT rate", "Defensive help consistency"],
    fitAnalysis: "Ingram brings an elite isolation scoring threat to relief Cade Cunningham of constant defensive double-teams. His playmaking and wing length would bolster the Pistons' frontcourt shot-creation quotient.",
    primaryBenefit: "playmaking"
  },
  {
    id: "fa-jimmy-butler",
    name: "Jimmy Butler",
    position: "SF",
    currentTeam: "Miami Heat",
    age: 36,
    tier: "Max Target",
    projectedSalary: 38.0,
    ppg: 20.8,
    rpg: 5.3,
    apg: 5.0,
    strengths: ["Lockdown Playoff Defense", "Elite Foul-Drawing rate", "Championship Toughness"],
    weaknesses: ["Low relative 3PT volume", "Age and health maintenance"],
    fitAnalysis: "Butler would immediately bring the legendary 'Bad Boys' grit back to Detroit. His ultimate defensive standard, playmaking from the elbow, and peerless physical leadership would provide invaluable mentoring for Holland and Thompson.",
    primaryBenefit: "veteran_experience"
  },
  {
    id: "fa-de-aaron-fox",
    name: "De'Aaron Fox",
    position: "PG",
    currentTeam: "Sacramento Kings",
    age: 28,
    tier: "Max Target",
    projectedSalary: 41.5,
    ppg: 26.6,
    rpg: 4.6,
    apg: 5.6,
    strengths: ["Blazing Paint Acceleration", "Clutch Scoring instincts", "Active Deflection hands"],
    weaknesses: ["Pulls from deep can be streaky", "Off-ball offensive gravity"],
    fitAnalysis: "Fox is an electric dual-guard option. Placing him alongside Cade Cunningham would form a terrifying dual-engine backcourt with unstoppable paint transition speed and clutch execution potential.",
    primaryBenefit: "playmaking"
  },
  {
    id: "fa-naz-reid",
    name: "Naz Reid",
    position: "C / PF",
    currentTeam: "Minnesota Timberwolves",
    age: 26,
    tier: "Premium Starter",
    projectedSalary: 23.5,
    ppg: 14.8,
    rpg: 5.3,
    apg: 1.6,
    strengths: ["Slick Off-dribble drives", "Elite Corner 3PT Spacing", "High Energy spark"],
    weaknesses: ["Defensive rebounding limits", "Friction defending fast combo guards"],
    fitAnalysis: "The former Sixth Man of the Year is an athletic offensive force. His ability to hit deep catch-and-shoot threes, attack slow centers off the bounce, and play with boundless hustle makes him an incredible offensive optimizer.",
    primaryBenefit: "shooting"
  },
  {
    id: "fa-kyrie-irving",
    name: "Kyrie Irving",
    position: "PG / SG",
    currentTeam: "Dallas Mavericks",
    age: 34,
    tier: "Max Target",
    projectedSalary: 37.5,
    ppg: 25.4,
    rpg: 5.0,
    apg: 5.2,
    strengths: ["Unmatchable Ball Handling", "Generational 3PT / Midrange Gravity", "Veteran Playoff Wisdom"],
    weaknesses: ["Interior defensive switching", "Durability projection"],
    fitAnalysis: "An elite offensive virtuoso. Irving's immaculate perimeter shooting and off-ball movement would give Detroit's core drivers unlimited room to work, providing championship scoring mechanics.",
    primaryBenefit: "shooting"
  },
  {
    id: "fa-rudy-gobert",
    name: "Rudy Gobert",
    position: "C",
    currentTeam: "Minnesota Timberwolves",
    age: 34,
    tier: "Premium Starter",
    projectedSalary: 30.0,
    ppg: 13.5,
    rpg: 12.4,
    apg: 1.2,
    strengths: ["Generational Rim Protection", "Screen Gravity & rolling", "Elite Rebounding"],
    weaknesses: ["Zero offensive range outside restricted area", "Perimeter speed mismatches on switches"],
    fitAnalysis: "Gobert's defensive presence would immediately turn Detroit into a top-5 defensive team. His rolling pressure and elite rebounding secure possessions and make up for raw paint weaknesses.",
    primaryBenefit: "defense"
  },
  {
    id: "fa-julius-randle",
    name: "Julius Randle",
    position: "PF",
    currentTeam: "Minnesota Timberwolves",
    age: 31,
    tier: "Max Target",
    projectedSalary: 30.5,
    ppg: 24.0,
    rpg: 9.2,
    apg: 5.0,
    strengths: ["Bully-Ball Frontcourt Scoring", "Strong Dribble Playmaking", "Rebounding motor"],
    weaknesses: ["Defensive closeout energy", "Turnover rates under hard double teams"],
    fitAnalysis: "Randle provides premium post presence, playmaking from the 4 spot, and robust scoring capabilities that would shift pressure off of Detroit's developing backcourt prospects.",
    primaryBenefit: "size"
  },
  {
    id: "fa-aaron-gordon",
    name: "Aaron Gordon",
    position: "PF / SF",
    currentTeam: "Denver Nuggets",
    age: 30,
    tier: "Premium Starter",
    projectedSalary: 24.0,
    ppg: 13.9,
    rpg: 6.5,
    apg: 3.5,
    strengths: ["Elite Lock-down Defensive Versatility", "immense Lob threat / Dunker spot", "Championship pedigree"],
    weaknesses: ["Streaky free throw shooter", "Self-creation from deep"],
    fitAnalysis: "Gordon provides elite multi-position defense, extreme athletic power, and can unlock secondary cutting spaces next to Jaden Ivey. An elite veteran addition who plays winning team basketball.",
    primaryBenefit: "defense"
  },
  {
    id: "fa-fred-vanvleet",
    name: "Fred VanVleet",
    position: "PG",
    currentTeam: "Houston Rockets",
    age: 32,
    tier: "Premium Starter",
    projectedSalary: 25.5,
    ppg: 16.8,
    rpg: 3.7,
    apg: 8.1,
    strengths: ["High-volume deep 3PT range", "Championship leadership and poise", "Elite team defense hands"],
    weaknesses: ["Below-average interior finishing", "Older guard physical height limits"],
    fitAnalysis: "VanVleet provides incredible off-ball spacing and veteran floor command. Putting him in rotation relieves ball pressure on Ivey and Cunningham, and brings elite professional habits to the gym.",
    primaryBenefit: "veteran_experience"
  },
  {
    id: "fa-dangelo-russell",
    name: "D'Angelo Russell",
    position: "PG / SG",
    currentTeam: "Los Angeles Lakers",
    age: 30,
    tier: "Premium Starter",
    projectedSalary: 20.0,
    ppg: 18.0,
    rpg: 3.1,
    apg: 6.3,
    strengths: ["Pick-and-roll precision", "Catch-and-shoot 3PT spacing", "Silky mid-range touch"],
    weaknesses: ["Point-of-attack lateral recovery", "Shot selection in high-pressure frames"],
    fitAnalysis: "D-Lo adds elite passing, elite floor spacing, and deep playoff backcourt experience. He is a premier off-ball weapon who can also run units as the chief floor general.",
    primaryBenefit: "shooting"
  },
  {
    id: "fa-norman-powell",
    name: "Norman Powell",
    position: "SG / SF",
    currentTeam: "Los Angeles Clippers",
    age: 33,
    tier: "Premium Starter",
    projectedSalary: 18.5,
    ppg: 17.6,
    rpg: 2.6,
    apg: 1.5,
    strengths: ["Blistering Catch-and-Shoot 3PT (40%+)", "Strong baseline driver", "Tough, rugged perimeter builder"],
    weaknesses: ["Playmaking progression under pressure", "Undersized on wing defense matchups"],
    fitAnalysis: "Powell is an efficient bucket-getter who will instantly fix Detroit's perimeter gravity issues. He adds elite off-ball movement and physical athletic finishes at the rim.",
    primaryBenefit: "shooting"
  },
  {
    id: "fa-bobby-portis",
    name: "Bobby Portis",
    position: "PF / C",
    currentTeam: "Milwaukee Bucks",
    age: 31,
    tier: "Valued Role Player",
    projectedSalary: 14.0,
    ppg: 13.5,
    rpg: 7.4,
    apg: 1.2,
    strengths: ["Intense energetic rebounder", "Reliable stretch space 3PT", "Elite bench unit scoring"],
    weaknesses: ["Lateral movement on perimeter guards", "Rim protection depth"],
    fitAnalysis: "Portis provides extreme hustle and high-level grit. His perimeter shooting and post scoring would instantly spark Detroit's reserve units with raw Detroit-style passion.",
    primaryBenefit: "size"
  },
  {
    id: "fa-clint-capela",
    name: "Clint Capela",
    position: "C",
    currentTeam: "Atlanta Hawks",
    age: 32,
    tier: "Valued Role Player",
    projectedSalary: 13.0,
    ppg: 11.2,
    rpg: 10.4,
    apg: 1.0,
    strengths: ["Elite offensive glass-crashing", "Proven PNJ lob threat & roller", "Solid drop-scheme paint anchor"],
    weaknesses: ["Zero perimeter shooting threat", "Post self-creation moves"],
    fitAnalysis: "Capela would provide Cade Cunningham with an elite, physical pick-and-roll screen and lob partner, while stabilizing Detroit's interior rebounding metrics.",
    primaryBenefit: "size"
  },
  {
    id: "fa-malcolm-brogdon",
    name: "Malcolm Brogdon",
    position: "PG / SG",
    currentTeam: "Washington Wizards",
    age: 33,
    tier: "Valued Role Player",
    projectedSalary: 12.0,
    ppg: 14.5,
    rpg: 4.1,
    apg: 5.1,
    strengths: ["High IQ floor navigation", "Strong size for position defense", "Excellent catch-and-shoot efficiency"],
    weaknesses: ["Durability history", "Decline in transition speed"],
    fitAnalysis: "A steady, high-efficiency guard who can balance and stabilize the second unit. Brogdon brings superb outside shooting and high defensive maturity.",
    primaryBenefit: "veteran_experience"
  },
  {
    id: "fa-gary-trent",
    name: "Gary Trent Jr.",
    position: "SG / SF",
    currentTeam: "Milwaukee Bucks",
    age: 27,
    tier: "Valued Role Player",
    projectedSalary: 14.5,
    ppg: 13.8,
    rpg: 2.3,
    apg: 1.5,
    strengths: ["High-Volume 3-Point Shooting", "Active Steal & Passing Lanes", "Durability"],
    weaknesses: ["Shot selection inside arc", "Defensive screen containment"],
    fitAnalysis: "Trent is an outstanding veteran floor-spacer who can immediately slot into a starting visual role. He has years of high-gravity spacing under his belt and plays with active defensive hand interference.",
    primaryBenefit: "shooting"
  },
  {
    id: "fa-derrick-jones",
    name: "Derrick Jones Jr.",
    position: "SF / PF",
    currentTeam: "Los Angeles Clippers",
    age: 29,
    tier: "Valued Role Player",
    projectedSalary: 11.5,
    ppg: 9.1,
    rpg: 3.8,
    apg: 1.0,
    strengths: ["Elite POA Wing Stopping", "Generational athletic lobs", "Active Weakside helper"],
    weaknesses: ["Streaky perimeter shooter", "Self-creation off bounce"],
    fitAnalysis: "Provides a reliable, athletic wing defensive option. He mimics Ausar Thompson's athletic utility but adds extra veteran defensive screen navigation, allowing the team to rotate lockdown wing segments.",
    primaryBenefit: "defense"
  },
  {
    id: "fa-caris-levert",
    name: "Caris LeVert",
    position: "SG / SF",
    currentTeam: "Cleveland Cavaliers",
    age: 31,
    tier: "Valued Role Player",
    projectedSalary: 11.0,
    ppg: 13.5,
    rpg: 3.3,
    apg: 4.8,
    strengths: ["Shifty off-dribble drive creator", "Active backcourt hands / steals", "Experienced bench unit engine"],
    weaknesses: ["Streaky 3PT efficiency", "Shot selection pacing"],
    fitAnalysis: "LeVert provides instant playmaking and downhill draft creation. He can play an elite secondary facilitator next to Cade or spark bench reserves with offensive punches.",
    primaryBenefit: "playmaking"
  },
  {
    id: "fa-jonas-valanciunas",
    name: "Jonas Valanciunas",
    position: "C",
    currentTeam: "Washington Wizards",
    age: 34,
    tier: "Valued Role Player",
    projectedSalary: 10.5,
    ppg: 12.0,
    rpg: 8.8,
    apg: 2.1,
    strengths: ["Sledgehammer screen-setting", "Elite physical low-post presence", "Infallible defensive glass cleaner"],
    weaknesses: ["Slow recovery on perimeter pick-and-roll", "High-volume defensive switching situations"],
    fitAnalysis: "Valanciunas is a hulking center who creates clean paths for Cade with bruising screen gravity. He holds down the glass and provides crucial physical interior protection.",
    primaryBenefit: "size"
  },
  {
    id: "fa-brook-lopez",
    name: "Brook Lopez",
    position: "C",
    currentTeam: "Milwaukee Bucks",
    age: 38,
    tier: "Valued Role Player",
    projectedSalary: 9.0,
    ppg: 11.8,
    rpg: 4.5,
    apg: 1.4,
    strengths: ["Elite deep-drop shot block", "High-volume deep 3PT stretch", "Unmatched veteran team communications"],
    weaknesses: ["Extremely slow foot speed", "Defensive rebounding volume limits"],
    fitAnalysis: "Brook Lopez is the prototypical spacing rim protector. Even at 38, his deep-drop capabilities and pick-and-pop perimeter accuracy would make him a perfect fit next to Ivey and Cade.",
    primaryBenefit: "defense"
  },
  {
    id: "fa-kelly-oubre",
    name: "Kelly Oubre Jr.",
    position: "SF / SG",
    currentTeam: "Philadelphia 76ers",
    age: 30,
    tier: "Valued Role Player",
    projectedSalary: 9.5,
    ppg: 14.1,
    rpg: 4.8,
    apg: 1.4,
    strengths: ["Energetic perimeter defense", "Strong downhill driving cuts", "Highly active off-ball scorer"],
    weaknesses: ["Playmaking vision under traffic", "Inconsistent 3-point range percentages"],
    fitAnalysis: "Oubre adds athleticism, size, and defensive hustle on the perimeter. His driving cuts provide excellent downhill support next to secondary distributors.",
    primaryBenefit: "defense"
  },
  {
    id: "fa-tj-mcconnell",
    name: "T.J. McConnell",
    position: "PG",
    currentTeam: "Indiana Pacers",
    age: 34,
    tier: "Valued Role Player",
    projectedSalary: 9.8,
    ppg: 9.6,
    rpg: 2.7,
    apg: 5.5,
    strengths: ["Elite Mid-Range Pullup", "Tenacious Full-court Press", "Vocal Leadership", "Instant Pace control"],
    weaknesses: ["Zero 3PT volume", "Undersized on switches"],
    fitAnalysis: "McConnell provides Detroit with elite veteran leadership and a high-iq backup master handler. He operates as an elite sparkplug who controls tempo and forces defensive turnovers.",
    primaryBenefit: "veteran_experience"
  },
  {
    id: "fa-luke-kennard",
    name: "Luke Kennard",
    position: "SG",
    currentTeam: "Memphis Grizzlies",
    age: 29,
    tier: "Valued Role Player",
    projectedSalary: 8.5,
    ppg: 9.2,
    rpg: 2.2,
    apg: 2.5,
    strengths: ["Generational catch-and-shoot depth (42%+)", "Smooth screen-escapes", "Secondary playmaking IQ"],
    weaknesses: ["Defensive physical switching limits", "Perimeter speed recovery"],
    fitAnalysis: "A former Piston and one of the finest pure snipers in modern basketball. Kennard's elite catch-and-shoot capability completely stretches the court, offering immense relief to Jaden Ivey.",
    primaryBenefit: "shooting"
  },
  {
    id: "fa-al-horford",
    name: "Al Horford",
    position: "C / PF",
    currentTeam: "Boston Celtics",
    age: 40,
    tier: "Vet Minimum",
    projectedSalary: 4.5,
    ppg: 7.8,
    rpg: 5.5,
    apg: 2.3,
    strengths: ["Supreme defensive positioning", "Reliable top-key 3PT spacing", "Championship composure & leadership"],
    weaknesses: ["Slow recovery on quick backcourt isolations", "Zero interior post-bruising presence"],
    fitAnalysis: "Horford is the ultimate professional. Signing him to tutor Detroit's young bigs while stretching the floor at center provides a blueprint of true veteran winning execution.",
    primaryBenefit: "veteran_experience"
  },
  {
    id: "fa-chris-paul",
    name: "Chris Paul",
    position: "PG",
    currentTeam: "San Antonio Spurs",
    age: 41,
    tier: "Vet Minimum",
    projectedSalary: 3.8,
    ppg: 6.8,
    rpg: 2.4,
    apg: 6.2,
    strengths: ["Future Hall-of-Fame playmaking", "Invaluable Guard tutor", "Elbow Mid-Range spacing"],
    weaknesses: ["Aged speed limits", "Strict switch targeting"],
    fitAnalysis: "CP3 is the undisputed king of mentoring young rising star guards. Signing him to tutor Cade Cunningham and Jaden Ivey while checking off veteran leadership is a masterstroke.",
    primaryBenefit: "veteran_experience"
  }
];

// Dynamically populate realistic advanced stats for Free Agents
const faStatsMap: Record<string, { darko: number; lebron: number; epm: number }> = {
  "fa-myles-turner": { darko: 1.8, lebron: 1.5, epm: 1.9 },
  "fa-brandon-ingram": { darko: 2.2, lebron: 1.7, epm: 2.1 },
  "fa-jimmy-butler": { darko: 3.2, lebron: 3.5, epm: 3.4 },
  "fa-de-aaron-fox": { darko: 2.9, lebron: 2.8, epm: 3.0 },
  "fa-naz-reid": { darko: 1.2, lebron: 1.0, epm: 1.1 },
  "fa-kyrie-irving": { darko: 3.0, lebron: 2.5, epm: 2.8 },
  "fa-rudy-gobert": { darko: 2.5, lebron: 3.1, epm: 2.6 },
  "fa-julius-randle": { darko: 2.0, lebron: 1.6, epm: 1.8 },
  "fa-aaron-gordon": { darko: 1.4, lebron: 1.5, epm: 1.3 },
  "fa-fred-vanvleet": { darko: 1.9, lebron: 2.1, epm: 1.8 },
  "fa-dangelo-russell": { darko: 0.8, lebron: 0.4, epm: 0.6 },
  "fa-norman-powell": { darko: 0.9, lebron: 0.5, epm: 0.7 },
  "fa-bobby-portis": { darko: 0.2, lebron: -0.1, epm: 0.1 },
  "fa-clint-capela": { darko: 0.6, lebron: 0.8, epm: 0.5 },
  "fa-malcolm-brogdon": { darko: 0.7, lebron: 0.5, epm: 0.6 },
  "fa-gary-trent": { darko: 0.1, lebron: -0.3, epm: -0.1 },
  "fa-derrick-jones": { darko: 0.8, lebron: 1.0, epm: 0.9 },
  "fa-caris-levert": { darko: 0.4, lebron: 0.1, epm: 0.3 },
  "fa-jonas-valanciunas": { darko: 0.5, lebron: 0.2, epm: 0.3 },
  "fa-brook-lopez": { darko: 1.1, lebron: 1.3, epm: 1.0 },
  "fa-kelly-oubre": { darko: 0.1, lebron: -0.2, epm: -0.1 },
  "fa-tj-mcconnell": { darko: 1.5, lebron: 1.8, epm: 1.6 },
  "fa-luke-kennard": { darko: 0.6, lebron: 0.4, epm: 0.5 },
  "fa-al-horford": { darko: 1.0, lebron: 1.2, epm: 0.9 },
  "fa-chris-paul": { darko: 1.2, lebron: 1.4, epm: 1.1 }
};

freeAgentsData.forEach(fa => {
  const stats = faStatsMap[fa.id];
  if (stats) {
    fa.darko = stats.darko;
    fa.lebron = stats.lebron;
    fa.epm = stats.epm;
  } else {
    fa.darko = Number((0.15 * fa.ppg + 0.05 * fa.rpg + 0.08 * fa.apg - 1.5).toFixed(1));
    fa.lebron = Number((0.12 * fa.ppg + 0.06 * fa.rpg + 0.06 * fa.apg - 1.3).toFixed(1));
    fa.epm = Number((0.18 * fa.ppg + 0.04 * fa.rpg + 0.05 * fa.apg - 1.7).toFixed(1));
  }
});

// Process draft prospects similarly (representing projective metrics)
draftProspectsData.forEach(p => {
  p.darko = Number((0.12 * p.projectedPpg + 0.05 * p.projectedRpg + 0.08 * p.projectedApg - 1.8).toFixed(1));
  p.lebron = Number((0.10 * p.projectedPpg + 0.06 * p.projectedRpg + 0.06 * p.projectedApg - 1.5).toFixed(1));
  p.epm = Number((0.15 * p.projectedPpg + 0.04 * p.projectedRpg + 0.05 * p.projectedApg - 2.0).toFixed(1));
});
